CREATE TABLE `insurance_db`.`contracts` (
  `insured_person_id` int unsigned NOT NULL COMMENT '被保険者番号',
  `contract_id` smallint unsigned NOT NULL COMMENT '契約番号',
  `contract_history_id` smallint unsigned NOT NULL COMMENT '契約履歴番号',
  `contract_start_date` varchar(8) NOT NULL COMMENT '契約開始日',
  `contract_end_date` varchar(8) NOT NULL COMMENT '契約終了日',
  `contract_end_reason` varchar(2) NOT NULL COMMENT '契約終了事由',
  `contract_maturity_date` varchar(8) NOT NULL COMMENT '契約満期日',
  `security_type` varchar(2) NOT NULL COMMENT '保障種類',
  `entry_age` tinyint unsigned NOT NULL COMMENT '加入年齢',
  `payment_method` varchar(1) NOT NULL COMMENT '払込方法',
  `insurance_money` int NOT NULL COMMENT '保険金',
  `premium` int NOT NULL COMMENT '掛金',
  `premium_payment_term` tinyint unsigned NOT NULL COMMENT '掛金払込期間',
  `contract_term` tinyint unsigned NOT NULL COMMENT '契約期間',
  `payment_expiration_age` tinyint unsigned NOT NULL COMMENT '払込満了年齢',
  `create_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日',
  PRIMARY KEY (`insured_person_id`,`contract_id`,`contract_history_id`),
  CONSTRAINT `contracts_ibfk_1` FOREIGN KEY (`insured_person_id`) REFERENCES `insured_persons` (`insured_person_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='契約情報テーブル'